# 국방 M&S RAG 시스템 설정
project:
  name: "Defense M&S RAG System"
  version: "1.0.0"
  description: "국방 모델링 및 시뮬레이션 문서 기반 RAG 시스템"

# Ollama 설정
ollama:
  host: "http://localhost:11434"
  model: "llama3:8b"
  embedding_model: "nomic-embed-text"
  temperature: 0.7
  max_tokens: 2048
  timeout: 60

# 벡터 데이터베이스 설정
vector_db:
  type: "chromadb"
  persist_directory: "./data/chroma_db"
  collection_name: "defense_ms_docs"
  embedding_dimension: 768
  similarity_threshold: 0.7

# 문서 처리 설정 (웹페이지 지원 추가)
document_processing:
  chunk_size: 1000
  chunk_overlap: 200
  supported_formats:
    - "pdf"
    - "txt"
    - "md"
    - "docx"
    - "webpage"
  pdf_extraction:
    method: "PyPDF2"
    preserve_layout: true
  text_splitting:
    method: "recursive"
    separators: ["\n\n", "\n", " ", ""]
  web_scraping:
    timeout: 30
    delay_between_requests: 1
    max_retries: 3
    user_agent: "Defense-RAG-System/1.0"

# RAG 시스템 설정 (프롬프트 엔지니어링 강화)
rag:
  retrieval:
    top_k: 5
    search_type: "similarity"
    score_threshold: 0.7
  generation:
    max_context_length: 4000
    system_prompt_template: |
      당신은 국방 모델링 및 시뮬레이션(M&S) 분야의 최고 전문가입니다.
      
      **전문 역량:**
      - 20년 이상의 국방 M&S 실무 경험
      - 국내외 M&S 표준 및 기술 동향에 대한 깊은 이해
      - 전투 효과 분석, 시뮬레이션 설계, VV&A 전문성
      - HLA, DIS, SISO 표준 전문가
      
      **답변 원칙:**
      1. 정확하고 기술적으로 정밀한 정보 제공
      2. 실무에 직접 적용 가능한 구체적 가이드
      3. 관련 표준, 절차, 모범사례 포함
      4. 불확실한 정보는 명시적으로 구분
      5. 한국의 국방 환경과 요구사항 고려
    user_prompt_template: |
      관련 문서 내용:
      {context}
      
      질문: {question}
      
      위 문서 내용을 참고하여 질문에 대해 전문적이고 정확한 답변을 해주세요.

# 로깅 설정
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: "./logs/rag_system.log"
  max_file_size: "10MB"
  backup_count: 5

# 국방 M&S 특화 설정
defense_ms:
  domains:
    - "지상전"
    - "해상전" 
    - "공중전"
    - "우주전"
    - "사이버전"
    - "합동작전"
  simulation_types:
    - "구성적 시뮬레이션"
    - "가상 시뮬레이션"
    - "실시간 시뮬레이션"
    - "혼합 시뮬레이션"
  standards:
    - "HLA (High Level Architecture)"
    - "DIS (Distributed Interactive Simulation)"
    - "SISO Standards"
    - "국방 M&S 표준"
  keywords:
    general: ["M&S", "모델링", "시뮬레이션", "VV&A", "검증", "확인"]
    technical: ["HLA", "DIS", "RTI", "FOM", "SOM", "Federation"]
    analysis: ["효과도", "분석", "평가", "측정", "지표"]

# 데이터 소스 설정
data_sources:
  local_documents:
    directory: "./docs/pdfs"
    auto_load: true
  web_sources:
    urls_file: "./data/ms_urls.txt"
    auto_load: false
  sample_data:
    directory: "./data/samples"
    enabled: true

# 캐시 설정
cache:
  enabled: true
  type: "memory"
  ttl: 3600
  max_size: 1000